In [2]:
import sklearn

print(sklearn.__version__)

0.24.1


In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_label = iris.target

print('iris target values: ', iris_label)
print('iris target names: ', iris.target_names)

iris target values:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target names:  ['setosa' 'versicolor' 'virginica']


In [2]:
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [3]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

In [4]:
dt_clf = DecisionTreeClassifier(random_state=11)

In [5]:
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [6]:
pred = dt_clf.predict(X_test)

In [8]:
from sklearn.metrics import accuracy_score

print(f'accuracy: {accuracy_score(y_test, pred):.4f}')

accuracy: 0.9333


In [9]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


In [10]:
keys = iris_data.keys()
print(f'keys for iris dataset: {keys}')

keys for iris dataset: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [13]:
print(f'\n feature_names type: {type(iris_data.feature_names)}')
print(f'\n feature_names shape: {len(iris_data.feature_names)}')
print(iris_data.feature_names)

print(f'\n target_names type: ', type(iris_data.target_names))
print(f'target_names shape: ', len(iris_data.target_names))
print(iris_data.target_names)

print(f'\n data type: {type(iris_data.data)}')
print(f'data shape: {iris_data.data.shape}')
print(iris_data.data)

print(f'\n target type: ', type(iris_data.target))
print(f'target shape: ', iris_data.target.shape)
print(iris_data.target)


 feature_names type: <class 'list'>

 feature_names shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names type:  <class 'numpy.ndarray'>
target_names shape:  3
['setosa' 'versicolor' 'virginica']

 data type: <class 'numpy.ndarray'>
data shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.

In [15]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris_data.data
train_label = iris_data.target
dt_clf.fit(train_data, train_label)

pred = dt_clf.predict(train_data)
print(f'accuracy: {accuracy_score(train_label, pred)}')

accuracy: 1.0


In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf = DecisionTreeClassifier()
iris_data = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)

In [17]:
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print(f'accuracy: {accuracy_score(y_test, pred):.4f}')

accuracy: 0.9556


In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

kfold = KFold(n_splits=5)
cv_accuracy = []
print(f'iris dataset size: {features.shape[0]}')

iris dataset size: 150


In [19]:
n_iter = 0
for train_index, test_index in kfold.split(features):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1

    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]

    print(f'cross validation accuracy: {accuracy}, train data size: {train_size}, test data size: {test_size}')
    print(f'#{n_iter} test set index: {test_index}')
    cv_accuracy.append(accuracy)

print(f'\n## averge accuracy: {np.mean(cv_accuracy)}')

cross validation accuracy: 1.0, train data size: 120, test data size: 30
#1 test set index: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
cross validation accuracy: 0.9667, train data size: 120, test data size: 30
#2 test set index: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
cross validation accuracy: 0.8667, train data size: 120, test data size: 30
#3 test set index: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]
cross validation accuracy: 0.9333, train data size: 120, test data size: 30
#4 test set index: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
cross validation accuracy: 0.7333, train data size: 120, test data size: 30
#5 test set index: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

##

In [24]:
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [26]:
kfold = KFold(n_splits=3)
n_iter = 0

for train_index, test_index in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(f'## cross validation: {n_iter}')
    print(f'train label data distribution:\n {label_train.value_counts()}')
    print(f'test label data distribution:\n {label_test.value_counts()}')

## cross validation: 1
train label data distribution:
 1    50
2    50
Name: label, dtype: int64
test label data distribution:
 0    50
Name: label, dtype: int64
## cross validation: 2
train label data distribution:
 0    50
2    50
Name: label, dtype: int64
test label data distribution:
 1    50
Name: label, dtype: int64
## cross validation: 3
train label data distribution:
 0    50
1    50
Name: label, dtype: int64
test label data distribution:
 2    50
Name: label, dtype: int64


In [27]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter =+ 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]

    print(f'## cross validation: {n_iter}')
    print(f'train label data distribution:\n {label_train.value_counts()}')
    print(f'test  label data distribution:\n {label_test.value_counts()}')

## cross validation: 1
train label data distribution:
 2    34
0    33
1    33
Name: label, dtype: int64
test  label data distribution:
 0    17
1    17
2    16
Name: label, dtype: int64
## cross validation: 1
train label data distribution:
 1    34
0    33
2    33
Name: label, dtype: int64
test  label data distribution:
 0    17
2    17
1    16
Name: label, dtype: int64
## cross validation: 1
train label data distribution:
 0    34
1    33
2    33
Name: label, dtype: int64
test  label data distribution:
 1    17
2    17
0    16
Name: label, dtype: int64


In [30]:
dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy = []

for train_index, test_index in skfold.split(features, label):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)

    n_iter += 1
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]

    print(f'cross validation accuracy: {accuracy}, train data size: {train_size}, test data size: {test_size}')
    print(f'#{n_iter} test set index: {test_index}')
    cv_accuracy.append(accuracy)

print(f'\n accuracy per cv: {np.round(cv_accuracy, 4)}')
print(f'\n## averge accuracy: {np.mean(cv_accuracy)}')

cross validation accuracy: 0.98, train data size: 100, test data size: 50
#1 test set index: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
cross validation accuracy: 0.94, train data size: 100, test data size: 50
#2 test set index: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]
cross validation accuracy: 0.98, train data size: 100, test data size: 50
#3 test set index: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

 accuracy per cv: [0.98 0.94 0.98]

## averge accuracy: 0.9666666666666667


In [31]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data['target']

scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print(f'accuracy per cross validation: {np.round(scores, 4)}')
print(f'mean cross validation accuracy: {np.round(np.mean(scores), 4)}')

accuracy per cross validation: [0.98 0.94 0.98]
mean cross validation accuracy: 0.9667


In [32]:
grid_parameters = {
    'max_depth': [1, 2, 3],
    'min_samples_split': [2, 3],
}

In [33]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

iris_data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)

dtree = DecisionTreeClassifier()

parameters = {'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]}

In [35]:
import pandas as pd

grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)
grid_dtree.fit(X_train, y_train)

scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [36]:
print(f'GridSearch CV best params: {grid_dtree.best_params_}')
print(f'GridSearch CV best score: {grid_dtree.best_score_}')

GridSearch CV best params: {'max_depth': 3, 'min_samples_split': 2}
GridSearch CV best score: 0.975


In [37]:
estimator = grid_dtree.best_estimator_

pred = estimator.predict(X_test)
print(f'Test dataset\'s accuracy: {accuracy_score(y_test, pred):.4f}')

Test dataset's accuracy: 0.9667


In [40]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', 'refrigerator', 'microwave oven', 'computer', 'fan', 'fan', 'mixer', 'mixer']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(f'encoded value: {labels}')

encoded value: [0 5 3 1 2 2 4 4]


In [41]:
print(f'encoding class: {encoder.classes_}')

encoding class: ['TV' 'computer' 'fan' 'microwave oven' 'mixer' 'refrigerator']


In [43]:
print(f'decoded original values: {encoder.inverse_transform([0, 5, 3, 1, 2, 2, 4, 4])}')

decoded original values: ['TV' 'refrigerator' 'microwave oven' 'computer' 'fan' 'fan' 'mixer'
 'mixer']


In [48]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', 'refrigerator', 'microwave oven', 'computer', 'fan', 'fan', 'mixer', 'mixer']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels = labels.reshape(-1, 1)
print(labels)

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('one hot encoded data')
print(oh_labels.toarray())
print('one hot encoded data\'s demension')
print(oh_labels.shape)

[[0]
 [5]
 [3]
 [1]
 [2]
 [2]
 [4]
 [4]]
one hot encoded data
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]]
one hot encoded data's demension
(8, 6)


In [49]:
import pandas as pd

df = pd.DataFrame({'item': ['TV', 'refrigerator', 'microwave oven', 'computer', 'fan', 'fan', 'mixer', 'mixer']})
df.head()

item
0              TV
1    refrigerator
2  microwave oven
3        computer
4             fan

In [50]:
pd.get_dummies(df)

item_TV  item_computer  item_fan  item_microwave oven  item_mixer  \
0        1              0         0                    0           0   
1        0              0         0                    0           0   
2        0              0         0                    1           0   
3        0              1         0                    0           0   
4        0              0         1                    0           0   
5        0              0         1                    0           0   
6        0              0         0                    0           1   
7        0              0         0                    0           1   

   item_refrigerator  
0                  0  
1                  1  
2                  0  
3                  0  
4                  0  
5                  0  
6                  0  
7                  0

In [52]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print(iris_df.head())
print(f'mean: {iris_df.mean()}')
print(f'var: {iris_df.var()}')

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
mean: sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
var: sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [53]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print(f'mean: {iris_df_scaled.mean()}')
print(f'var: {iris_df_scaled.var()}')

mean: sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
var: sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [54]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print(f'features\'s minimum value: {iris_df_scaled.min()}')
print(f'features\'s maximum value: {iris_df_scaled.max()}')

features's minimum value: sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
features's maximum value: sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [55]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(0, 11).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1, 1)

print(train_array, test_array)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]] [[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [56]:
scaler = MinMaxScaler()

scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print(f'original data: {np.round(train_array.reshape(-1), 2)}')
print(f'scaled data: {np.round(train_scaled.reshape(-1), 2)}')

original data: [ 0  1  2  3  4  5  6  7  8  9 10]
scaled data: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [57]:
scaler.fit(test_array)
test_scaled = scaler.transform(test_array)

print(f'original data: {np.round(test_array.reshape(-1), 2)}')
print(f'scaled data: {np.round(test_scaled.reshape(-1), 2)}')

original data: [0 1 2 3 4 5]
scaled data: [0.  0.2 0.4 0.6 0.8 1. ]


In [58]:
scaler = MinMaxScaler()

scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print(f'original data: {np.round(train_array.reshape(-1), 2)}')
print(f'scaled data: {np.round(train_scaled.reshape(-1), 2)}')

test_scaled = scaler.transform(test_array)

print(f'original data: {np.round(test_array.reshape(-1), 2)}')
print(f'scaled data: {np.round(test_scaled.reshape(-1), 2)}')

original data: [ 0  1  2  3  4  5  6  7  8  9 10]
scaled data: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
original data: [0 1 2 3 4 5]
scaled data: [0.  0.1 0.2 0.3 0.4 0.5]
