In [10]:
import numpy as np

R = np.array([
    [4, np.NaN, np.NaN, 2, np.NaN],
    [np.NaN, 5, np.NaN, 3, 1],
    [np.NaN, np.NaN, 3, 4, 4],
    [5, 2, 1, 2, np.NaN],
])
num_users, num_items= R.shape
K = 3

np.random.seed(1)
P = np.random.normal(scale=1./K, size=(num_users, K))
Q = np.random.normal(scale=1./K, size=(num_items, K))

In [11]:
from sklearn.metrics import mean_squared_error

def get_rmse(R, P, Q, non_zeros):
    full_pred_matrix = np.dot(P, Q.T)

    x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)

    return rmse

In [12]:
non_zeros = [ (i, j, R[i, j]) for i in range(num_users) for j in range(num_items) if R[i, j] > 0 ]

steps = 1000
learning_rate= 0.01
r_lambda = 0.01

for step in range(steps):
    for i, j, r in non_zeros:
        eij = r - np.dot(P[i, :], Q[j, :].T)
        P[i, :] = P[i, :] + learning_rate * (eij * Q[j, :] - r_lambda * P[i, :])
        Q[j, :] = Q[j, :] + learning_rate * (eij * P[i, :] - r_lambda * Q[j, :])

    rmse = get_rmse(R, P, Q, non_zeros)

    if (step % 50) == 0:
        print(f'step: {step}, rmse: {rmse}')

step: 0, rmse: 3.2388050277987723
step: 50, rmse: 0.4876723101369648
step: 100, rmse: 0.1564340384819247
step: 150, rmse: 0.07455141311978046
step: 200, rmse: 0.04325226798579314
step: 250, rmse: 0.029248328780878973
step: 300, rmse: 0.022621116143829466
step: 350, rmse: 0.019493636196525135
step: 400, rmse: 0.018022719092132704
step: 450, rmse: 0.01731968595344266
step: 500, rmse: 0.016973657887570753
step: 550, rmse: 0.016796804595895633
step: 600, rmse: 0.01670132290188466
step: 650, rmse: 0.01664473691247669
step: 700, rmse: 0.016605910068210026
step: 750, rmse: 0.016574200475705
step: 800, rmse: 0.01654431582921597
step: 850, rmse: 0.01651375177473524
step: 900, rmse: 0.01648146573819501
step: 950, rmse: 0.016447171683479155


In [13]:
pred_matrix = np.dot(P, Q.T)
print(pred_matrix)

[[3.99062329 0.89653623 1.30649077 2.00210666 1.66340846]
 [6.69571106 4.97792757 0.97850229 2.98066034 1.0028451 ]
 [6.67689303 0.39076095 2.98728588 3.9769208  3.98610743]
 [4.96790858 2.00517956 1.00634763 2.01691675 1.14044567]]
