In [2]:
import numpy as np

array1 = np.array([1, 2, 3])
print('array1 type: ', type(array1))
print('array1 shape: ', array1.shape)

array2 = np.array([[1, 2, 3,], [2, 3, 4]])

print('array2 type: ', type(array2))
print('array2 shape: ', array2.shape)

array3 = np.array([[1, 2, 3,]])
print('array3 type: ', type(array3))
print('array3 shape: ', array3.shape)

array1 type:  <class 'numpy.ndarray'>
array1 shape:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2 shape:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3 shape:  (1, 3)


In [3]:
print(f'array1: {array1.ndim}, array2: {array2.ndim}, array3: {array3.ndim}')

array1: 1, array2: 2, array3: 2


In [4]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [5]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [6]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [7]:
array2 = np.array([[1, 2, 3], [2, 3, 4]])

print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1)) 

15
[3 5 7]
[6 9]


In [8]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [9]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [10]:
array1 = np.arange(10)
print('array1: \n', array1)

array2 = array1.reshape(2, 5)
print('array2: \n', array2)

array3 = array1.reshape(5, 2)
print('array3: \n', array3)

array1: 
 [0 1 2 3 4 5 6 7 8 9]
array2: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
print('array2: \n', array2)

array3 = array1.reshape(5, -1)
print('array2 shape:', array2.shape)
print('array2: \n', array2)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array2: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape: (5, 2)
array3: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1 = np.arange(5)
array2d_1 = array1.reshape(-1, 1)
print('array2d_1 shape: ', array2d_1.shape)
print('array2d_1: \n', array2d_1)

array1d = array2d_1.reshape(-1,)
print('array1d shape: ', array1d.shape)
print('array1d: \n', array1d)

array2d_1 shape:  (5, 1)
array2d_1: 
 [[0]
 [1]
 [2]
 [3]
 [4]]
array1d shape:  (5,)
array1d: 
 [0 1 2 3 4]


In [ ]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [ ]:
array1.reshape(-1, -1)

ValueError: can only specify one unknown dimension

In [ ]:
array1 = np.arange(start=1, stop=10)
print('array1: ', array1)

value = array1[2]
print('value: ', value)
print(type(value))

array1:  [1 2 3 4 5 6 7 8 9]
value:  3
<class 'numpy.int64'>


In [ ]:
print('the last value: ', array1[-1])
print('the second last value: ', array1[-2])

the last value:  9
the second last value:  8


In [ ]:
array1[0] = 9
array1[8] = 0
print('array1: ', array1)

array1:  [9 2 3 4 5 6 7 8 0]


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

print(array2d)

print(array2d[0, 0])
print(array2d[0, 1])
print(array2d[1, 0])
print(array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
4
9


In [ ]:
array1 = np.arange(start=1, stop=10)
print(array1)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print(array2d[0:2, 0:2])
print(array2d[1:3, 0:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

array3 = array2d[[0, 1], 2]
print(array3, array3.tolist())

array4 = array2d[[0, 2], 0:2]
print(array4, array4.tolist())

array5 = array2d[[0,1]]
print(array5, array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6] [3, 6]
[[1 2]
 [7 8]] [[1, 2], [7, 8]]
[[1 2 3]
 [4 5 6]] [[1, 2, 3], [4, 5, 6]]


In [ ]:
array1d = np.arange(start=1, stop=10)
print(array1d)

[1 2 3 4 5 6 7 8 9]


In [ ]:
print(array1d > 5)

var1 = array1d > 5
print('var1: ', var1)
print(type(var1))

[False False False False False  True  True  True  True]
var1:  [False False False False False  True  True  True  True]
<class 'numpy.ndarray'>


In [ ]:
print(array1d)
array3 = array1d[array1d > 5]
print(array3)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]


In [ ]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print(array3)

[6 7 8 9]


In [ ]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print(array4)

[6 7 8 9]


In [ ]:
array1d = np.arange(start=1, stop=10)
target = []

for i in range(0, 9):
    if array1d[i] > 5:
        target.append(array1d[i])

array_selected = np.array(target)
print(array_selected)

[6 7 8 9]


In [ ]:
print(array1d[array1d > 5])

[6 7 8 9]


In [ ]:
org_array = np.array([3, 1, 9, 5])
print(org_array)

sort_array1 = np.sort(org_array)
print(sort_array1)
print(org_array)

sort_array2 = org_array.sort()
print(sort_array2)
print(org_array)

[3 1 9 5]
[1 3 5 9]
[3 1 9 5]
None
[1 3 5 9]


In [ ]:
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [ ]:
array2d = np.array([[8, 12],
                    [7, 1]])
print(array2d)

sort_array2d_axis0 = np.sort(array2d, axis=0)
print(sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1)

[[ 8 12]
 [ 7  1]]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [15]:
org_array = np.array([3, 1, 9, 5])
print(np.sort(org_array))

sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(sort_indices)


[1 3 5 9]
<class 'numpy.ndarray'>
[1 0 3 2]


In [18]:
org_array = np.array([3, 1, 9, 5])
print(np.sort(org_array)[::-1])

sort_indices_desc = np.argsort(org_array)[::-1]
print(sort_indices_desc)

[9 5 3 1]
[2 3 0 1]


In [21]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samule'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices = np.argsort(score_array)
print(sort_indices)

name_array_sort = name_array[sort_indices]
print(name_array_sort)
score_array_sort = score_array[sort_indices]
print(score_array_sort)


[0 2 4 1 3]
['John' 'Sarah' 'Samule' 'Mike' 'Kate']
[78 84 88 95 98]


In [24]:
A = np.array([[1, 2, 3],[4, 5, 6]])
B = np.array([[7,8],[9,10],[11,12]])

dot_product = np.dot(A, B)
print(dot_product)

[[ 58  64]
 [139 154]]


In [26]:
A = np.array([[1, 2, 3],[4, 5, 6]])

transpose_mat = np.transpose(A)
print(transpose_mat)

[[1 4]
 [2 5]
 [3 6]]
